//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_CreateUser_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_CreateUser_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
  
    ViewBag.Title = "Register User";
    Layout = null;


#line default
#line hidden

#line 3 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
using (Html.BeginForm()) 
{
    

#line default
#line hidden

#line 4 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
                            
    
    

#line default
#line hidden

#line 6 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
       __o = Html.LabelFor(model => model.LoginName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 8 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.EditorFor(model => model.LoginName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.ValidationMessageFor(model => model.LoginName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
       __o = Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 11 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 12 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
       __o = Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 14 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 15 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" });


#line default
#line hidden

#line 16 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
       __o = Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 17 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 18 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" });


#line default
#line hidden

#line 19 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
       __o = Html.LabelFor(model => model.PhoneNo, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 20 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.EditorFor(model => model.PhoneNo, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 21 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.ValidationMessageFor(model => model.PhoneNo, "", new { @class = "text-danger" });


#line default
#line hidden

#line 22 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
       __o = Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 23 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 24 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
           __o = Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" });


#line default
#line hidden

#line 25 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
          
}

#line default
#line hidden

#line 26 "C:\Users\panka\AppData\Local\Temp\8BF5E8C9697790593214F10365F081C0BCD2\2\LoyaltyReward\Views\User\CreateUser.cshtml"
                                         __o = Html.ActionLink("SignIn", "UserLogin");


#line default
#line hidden
}
}
}
